src/menu/urls.py
from django.conf.urls import url

from .views import (
    menu_list,
    menu_detail,
    cat_list,
    cat_detail,
    )
from .api import (
    CategoriesCreateAPIView,
    CategoriesListAPIView,
    CategoriesRetrieveAPIView,
    CategoriesRetrieveDestroyAPIView,
    CategoriesRetrieveUpdateAPIView,
    MenuCreateAPIView,
    MenuListAPIView,
    MenuRetrieveAPIView,
    MenuRetrieveDestroyAPIView,
    MenuRetrieveUpdateAPIView,
    )

urlpatterns = [
    url(r'^$',
        menu_list,
        name="menu_list"
        ),
    url(r'^category/$',
        cat_list,
        name="cat_list"
        ),
    url(r'^category/details/(?P<slug>[\w-]+)/$',
        cat_detail,
        name="cat_detail"
        ),
    url(r'^details/(?P<slug>[\w-]+)/$',
        menu_detail,
        name="menu_detail"
        ),
    # menu api
    url(r'^api/$',
        MenuListAPIView.as_view(),
        name="menu_list_api"
        ),
    url(r'^api/create/$',
        MenuCreateAPIView.as_view(),
        name="menu_create_api"
        ),
    url(r'^api/(?P<slug>[\w-]+)/$',
        MenuRetrieveAPIView.as_view(),
        name="menu_detail_api"
        ),
    url(r'^api/(?P<slug>[\w-]+)/update/$',
        MenuRetrieveUpdateAPIView.as_view(),
        name="menu_update_api"
        ),
    url(r'^api/(?P<slug>[\w-]+)/destroy/$',
        MenuRetrieveDestroyAPIView.as_view(),
        name="menu_destroy_api"
        ),
    # category api
    url(r'^category/api/$',
        CategoriesListAPIView.as_view(),
        name="cat_list_api"
        ),
    url(r'^category/api/create/$',
        CategoriesCreateAPIView.as_view(),
        name="cat_create_api"
        ),
    url(r'^category/api/(?P<slug>[\w-]+)/$',
        CategoriesRetrieveAPIView.as_view(),
        name="cat_detail_api"
        ),
    url(r'^category/api/(?P<slug>[\w-]+)/update/$',
        CategoriesRetrieveUpdateAPIView.as_view(),
        name="cat_update_api"
        ),
    url(r'^category/api/(?P<slug>[\w-]+)/destroy/$',
        CategoriesRetrieveDestroyAPIView.as_view(),
        name="cat_destroy_api"
        ),
]

src/restaurant/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from index.views import home, about
from contact.views import contact


urlpatterns = [
    url(r'^$', home, name="home"),
    url(r'^about/$', about, name="about"),
    url(r'^contact/$', contact, name="contact_us"),
    url(r'^admin/', admin.site.urls),
    url(r'^menu/', include('menu.urls', namespace='menu')),
    url(r'^api-auth/', include(
        'rest_framework.urls',
        namespace='rest_framework'
        )),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
        )
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
        )

src/index/templates/index/about.html
{% extends 'index/base.html' %}

{% block title %} About | {{ block.super }}{% endblock title %}

{% block content %}
<h1>About US</h1>
<hr>
<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
Why do we use it?</p>

<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).
</p>


<p>The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.</p>

{% endblock content %}

src/index/templates/index/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %} Restaurant Website {% endblock title %}</title>

<!--         <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <link rel="stylesheet" href='{% static "css/base.css" %}'>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous"> -->

        <link rel="stylesheet" href='{% static "css/base.css" %}'>
        <link rel="stylesheet" href='{% static "css/bootstrap.min.css" %}'>
        <link rel="stylesheet" href='{% static "css/bootstrap-theme.min.css" %}'>

    </head>
    <body>
        {% include "index/navbar.html" %}
            <div class="container" style="padding-top: 80px;" >
                {% block content %}

                {% endblock content %}
            </div>
        {% include "index/footer.html" %}

        <script type="text/javascript" src="{% static 'js/jquery.min.js' %}" ></script>
        <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}" ></script>

<!--         <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script> -->
    </body>
</html>

src/index/templates/index/footer.html
<hr>
<footer class="footer">

    <!--Footer Links-->
    <div class="container-fluid">
        <div class="row">
            <!--First column-->
            <div class="col-md-6">
                <h5 class="title">Footer Content</h5>
                <p>Here you can use rows and columns here to organize your footer content.</p>
            </div>
            <!--/.First column-->
            <!--Second column-->
            <div class="col-md-6">
                <h5 class="title">Links</h5>
                <ul>
                    <li><a href="{% url 'home' %}">Home </a></li>
                    <li><a href="{% url 'menu:menu_list' %}">Menu</a></li>
                    <li><a href="{% url 'menu:cat_list' %}">Categories</a></li>
                </ul>
            </div>
            <!--/.Second column-->
        </div>
    </div>
    <!--/.Footer Links-->
    <!--Copyright-->
    <div class="footer-copyright">
        <div class="container-fluid">
            © 2017 Copyright: <a href="http://127.0.0.1:8000/"> restaurant.com</a>
        </div>
    </div>
    <!--/.Copyright-->
</footer>
<br>

src/index/templates/index/home.html
{% extends 'index/base.html' %}

{% block content %}
<div class="jumbotron">
  <h1>Restaurant Website!</h1>
  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer eget aliquet metus, at dignissim elit. Nunc et sem sapien. Suspendisse pharetra porttitor dui et hendrerit. Phasellus malesuada, augue ut vulputate fringilla, felis risus gravida nulla, id consectetur est mauris id purus. Nulla facilisi.</p>
  <p><a class="btn btn-primary btn-lg" href="{% url 'menu:menu_list' %}" role="button">Our Menu</a>
  <a class="btn btn-default btn-lg" href="{% url 'contact_us' %}" role="button">Contact US</a></p>
</div>

<div class="container">
    <h2>Featured Items</h2>
    <hr>
{% for q in queryset %}
<div class="col-sm-5 col-md-3">
    <div class="thumbnail">
    {% if q.img %}
      <img src="{{ q.img.url }}" alt="..." style="width:232px;height:192px;">
      {% endif %}
      <div class="caption">
        <h5><b>{{ q.item }}</b></h5>
        <p>Price: {{ q.price }}$</p>
        <p><a href="{{ q.get_absolute_url }}" class="btn btn-default" role="button">Details</a></p>
      </div>
    </div>
  </div>
{% endfor %}
<div>
<a href="{% url 'menu:menu_list' %}">View All Items ---></a>
</div>
</div>
{% endblock content %}

src/index/templates/index/navbar.html
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'home' %}">Restaurant</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="{% url 'home' %}">Home </a></li>
        <li><a href="{% url 'menu:menu_list' %}">Menu</a></li>
        <li><a href="{% url 'menu:cat_list' %}">Categories</a></li>
       <!--  <li class="dropdown">
          <a href="{% url 'menu:cat_list' %}" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories <span class="caret"></span></a>
          <ul class="dropdown-menu">
            {% for obj in nav_qs %}
              <li><a href="{{ obj.get_absolute_url }}">{{ obj.cat_name }}</a></li>
              <li role="separator" class="divider"></li>
            {% endfor %}
          </ul>
        </li> -->
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'about' %}">About Us</a></li>
        <li><a href="{% url 'contact_us' %}">Contact Us</a></li> 
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>